update checksum
Homebrew/homebrew-cask-drivers pull request #1818
Opened 2020-10-12 16:52 UTC by albdv

- [ x ] `brew cask audit --download {{cask_file}}` is error-free.
- [ x ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ x ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-drivers/pulls) for the same update.
- [ x ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

It seems like vendor released application with the same version but with different sha2 checksum. Here is a fix.
Please take a look.

2020-10-12 19:46 UTC, vitorgalvao requested changes

2020-10-12 19:46 UTC, vitorgalvao commented on Casks/concept2-utility.rb
> +  desc "Is a free software available from Concept2 to manage your PM"
Everything before “manage your PM” is fluff and can be cut. But I don’t know what a “PM” is in this context.

2020-10-13 11:24 UTC, albdv commented on Casks/concept2-utility.rb
> +  desc "Is a free software available from Concept2 to manage your PM"
@vitorgalvao updated. does it looks better now from your point of view?

2020-10-13 14:02 UTC, vitorgalvao approved these changes

2020-10-13 23:22 UTC, miccal approved these changes

2020-10-14 00:17 UTC, merged