Update corsair-icue from 3.36.125 to 3.38.61
Homebrew/homebrew-cask-drivers pull request #2221
Opened 2021-05-13 23:29 UTC by cho-m

Created with `brew bump-cask-pr`.

2021-05-14 05:37 UTC, miccal commented
Strange:
```
bash 5.1.8   /Users/miccal   32
|-> /usr/bin/curl https://www.corsair.com/us/en/downloads/search?search=macos
"<div class=\"item\" style=\"display:block\"><div class=\"thumb\"><img src=\"/corsairmedia/sys_master/productcontent/iCUE-product_thumb.jpg\"></div><div class=\"details\"><input id=\"driverId\" type=\"hidden\" name=\"driverId\"  value=\"CORSAIR iCUE macOS 4.9.350\" /><div class=\"product_name\">CORSAIR iCUE macOS v4.9.350</div><div class=\"product_category\" style=\"display:none\">null</div><div class=\"download_name\"><p class=\"name\">macOS</p><span class=\"version\">4.9.350</span> | <span class=\"date\">03/19/2021</span></div><div class=\"download_url\"><a class=\"popup-with-form\" href=\"#download_form_1\" data-id=\"https://downloads.corsair.com/Files/CUE/iCUE-4.9.350-release.dmg\" data-url=\"https://downloads.corsair.com/Files/CUE/iCUE-4.9.350-release.dmg\"><img class=\"dl\" src=\"//cwsmgmt.corsair.com/responsive/img/downloads/cta_dk.png\"></a></div></div></div><div class=\"item\" style=\"display:block\"><div class=\"thumb\"><img src=\"/corsairmedia/sys_master/productcontent/iCUE-product_thumb.jpg\"></div><div class=\"details\"><input id=\"driverId\" type=\"hidden\" name=\"driverId\"  value=\"CORSAIR iCUE macOS 3.38.61\" /><div class=\"product_name\">CORSAIR iCUE macOS v3.38.61</div><div class=\"product_category\" style=\"display:none\">Cor_Products_iCue_Compatibility</div><div class=\"download_name\"><p class=\"name\">macOS</p><span class=\"version\">3.38.61</span> | <span class=\"date\">01/15/2021</span></div><div class=\"download_url\"><a class=\"popup-with-form\" href=\"#download_form_1\" data-id=\"https://downloads.corsair.com/Files/CUE/iCUE-3.38.61-release.dmg\" data-url=\"https://downloads.corsair.com/Files/CUE/iCUE-3.38.61-release.dmg\"><img class=\"dl\" src=\"//cwsmgmt.corsair.com/responsive/img/downloads/cta_dk.png\"></a></div></div></div><div class=\"item\" style=\"display:block\"><div class=\"thumb\"><img src=\"/corsairmedia/sys_master/productcontent/iCUE-product_thumb.jpg\"></div><div class=\"details\"><input id=\"driverId\" type=\"hidden\" name=\"driverId\"  value=\"CORSAIR iCUE macOS 3.37.140\" /><div class=\"product_name\">CORSAIR iCUE macOS v3.37.140</div><div class=\"product_category\" style=\"display:none\">Cor_Products_iCue_Compatibility</div><div class=\"download_name\"><p class=\"name\">macOS</p><span class=\"version\">3.37.140</span> | <span class=\"date\">01/11/2021</span></div><div class=\"download_url\"><a class=\"popup-with-form\" href=\"#download_form_1\" data-id=\"https://downloads.corsair.com/Files/CUE/iCUE-3.37.140-release.dmg\" data-url=\"https://downloads.corsair.com/Files/CUE/iCUE-3.37.140-release.dmg\"><img class=\"dl\" src=\"//cwsmgmt.corsair.com/responsive/img/downloads/cta_dk.png\"></a></div></div></div><div class=\"item\" style=\"display:block\"><div class=\"thumb\"><img src=\"/corsairmedia/sys_master/productcontent/iCUE-product_thumb.jpg\"></div><div class=\"details\"><input id=\"driverId\" type=\"hidden\" name=\"driverId\"  value=\"CORSAIR iCUE macOS 3.36.125\" /><div class=\"product_name\">CORSAIR iCUE macOS v3.36.125</div><div class=\"product_category\" style=\"display:none\">Cor_Products_iCue_Compatibility</div><div class=\"download_name\"><p class=\"name\">macOS</p><span class=\"version\">3.36.125</span> | <span class=\"date\">12/04/2020</span></div><div class=\"download_url\"><a class=\"popup-with-form\" href=\"#download_form_1\" data-id=\"https://downloads.corsair.com/Files/CUE/iCUE-3.36.125-release.dmg\" data-url=\"https://downloads.corsair.com/Files/CUE/iCUE-3.36.125-release.dmg\"><img class=\"dl\" src=\"//cwsmgmt.corsair.com/responsive/img/downloads/cta_dk.png\"></a></div></div></div><div class=\"item\" style=\"display:block\"><div class=\"thumb\"><img src=\"/corsairmedia/sys_master/productcontent/drivers_CORSAIR-CUE-SDK.jpg\"></div><div class=\"details\"><input id=\"driverId\" type=\"hidden\" name=\"driverId\"  value=\"CORSAIR iCUE SDK macOS\" /><div class=\"product_name\">CORSAIR iCUE SDK macOS</div><div class=\"product_category\" style=\"display:none\">Cor_Products_iCue_Compatibility</div><div class=\"download_name\"><p class=\"name\">SOFTWARE</p><span class=\"version\">3.0.361</span> | <span class=\"date\">10/15/2020</span></div><div class=\"download_url\"><a class=\"popup-with-form\" href=\"#download_form_1\" data-id=\"https://downloads.corsair.com/Files/CUE/CUESDK_3.0.361.dmg\" data-url=\"https://downloads.corsair.com/Files/CUE/CUESDK_3.0.361.dmg\"><img class=\"dl\" src=\"//cwsmgmt.corsair.com/responsive/img/downloads/cta_dk.png\"></a></div></div></div><div class=\"item\" style=\"display:block\"><div class=\"thumb\"></div><div class=\"details\"><input id=\"driverId\" type=\"hidden\" name=\"driverId\"  value=\"Thunderbolt Dock Utility\" /><div class=\"product_name\">Thunderbolt Dock Utility (macOS only)</div><div class=\"product_category\" style=\"display:none\">null</div><div class=\"download_name\"><p class=\"name\">null</p><span class=\"version\">1.3.0</span> | <span class=\"date\">09/24/2020</span></div><div class=\"download_url\"><a class=\"popup-with-form\" href=\"#download_form_1\" data-id=\"https://downloads.corsair.com/Files/Elgato/Corsair_Thunderbolt_Dock_Software_1.3.0m.dmg\" data-url=\"https://downloads.corsair.com/Files/Elgato/Corsair_Thunderbolt_Dock_Software_1.3.0m.dmg\"><img class=\"dl\" src=\"//cwsmgmt.corsair.com/responsive/img/downloads/cta_dk.png\"></a></div></div></div><input id=\"pro_tip_hidden\" type=\"hidden\"  value=\"\" />
```

2021-05-14 05:48 UTC, cho-m commented
My local system fails with same error as CI.

The corsair site doesn't seem to like access without cookies. Returns 403 error:
```console
❯ curl -I "https://www.corsair.com/us/en/downloads/search?search=macos"
HTTP/1.1 403 Forbidden
...
```

If I include my browser cookie, it works:
```console
❯ curl -I 'https://www.corsair.com/us/en/downloads/search?search=macos' \
  -H 'Cookie: idauto-lang=en; ROUTE= .........

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 1254
Content-Type: text/html
```

2021-05-14 05:52 UTC, miccal commented
Hmm, strange that it works from my end both with the system `curl` and my `brew`'ed `curl` without a cookie.

2021-05-14 05:54 UTC, miccal commented
@samford any ideas for this one?

2021-05-14 16:36 UTC, samford requested changes

2021-05-14 16:36 UTC, samford commented on Casks/corsair-icue.rb
> +    regex(/CORSAIR\s*iCUE\s*macOS\s*(\d+(?:\.\d+)*)/i)
General feedback about this particular `livecheck` block before getting into the `403` issue:

* When `strategy` is required it should appear after the other method calls (e.g., `regex`). We don't have audits yet to enforce the order of items in the `livecheck` block but basically `strategy` should come after the other methods because we sometimes need the other `livecheck` block information (e.g., `url`, `regex`) to be defined before it's used in a `strategy` block. Standardizing on a certain order even when a `strategy` block isn't being used means that it's easy to add a `strategy` block in the future if it's needed.
* Don't use `strategy` when it's not required. That is, if `brew livecheck --debug <formula/cask>` gives you the same strategy with and without the `strategy` call and you're not using a `strategy` block, you shouldn't use `strategy`. This is mentioned in the [`brew livecheck` documentation](https://docs.brew.sh/Brew-Livecheck#general-guidelines), so please be mindful of it. Using `strategy` when it's not required reduces livecheck's flexibility and and can increase the maintenance involved.

---

The download page uses Imperva/Incapsula, so the `livecheck` block will work/fail depending on whether Incapsula takes issue with your browser, internet connection, etc. As expected, this returns a `403 Forbidden` response when I test it using a VPN and works fine when I don't.

It works when you provide the cookies from your browser because the `incap_ses_*` cookie(s) tell Incapsula that you've already been verified as good and it's fine to proceed. Even if we added support for defining a cookie in a `livecheck` block, it wouldn't solve this particular issue because the Incapsula session will expire (i.e., the cookie's not good forever).

From my perspective, I don't think there's anything we can do in practical terms to deal with Incapsula in this context. Since we know this `livecheck` block would only work inconsistently, it may be better to simply skip it. It certainly wouldn't be the first formula/cask that we can't write a working `livecheck` block for because of an upstream issue.

```suggestion
    skip "Download page uses Imperva/Incapsula"
```

2021-05-17 03:16 UTC, miccal approved these changes

2021-05-17 03:16 UTC, merged