Update asix-ax88179 with macOS 11.0 driver
Homebrew/homebrew-cask-drivers pull request #2231
Opened 2021-05-19 07:15 UTC by ericswpark

Closes #2226

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

2021-05-19 23:15 UTC, vitorgalvao requested changes

2021-05-19 23:15 UTC, vitorgalvao commented on Casks/asix-ax88179.rb
>    sha256 :no_check
This should probably be set.

2021-05-19 23:15 UTC, vitorgalvao commented on Casks/asix-ax88179.rb
> +  if MacOS.version <= :catalina
Instead of using conditionals multiple times, use them *once* and set every specific thing in there.

2021-05-20 01:52 UTC, ericswpark commented
@vitorgalvao pushed another commit with your suggested changes, could you please take a look? Thanks.

2021-05-20 20:35 UTC, ericswpark commented on Casks/asix-ax88179.rb
> +    installer manual: "ASIX_USB_Device_Installer_v#{version.before_comma}.pkg"
Not sure, it was `installer manual:` originally.

2021-05-21 20:43 UTC, vitorgalvao commented on Casks/asix-ax88179.rb
> +    installer manual: "ASIX_USB_Device_Installer_v#{version.before_comma}.pkg"
Let’s change to PKG. Whatever reason we hadn’t like that may have been fixed by now.

2021-05-21 20:45 UTC, vitorgalvao submitted a review, later dismissed

2021-05-23 11:08 UTC, ericswpark commented
@vitorgalvao it seems like the SHA256 hash doesn't stay constant:
https://github.com/Homebrew/homebrew-cask-drivers/pull/2231/checks?check_run_id=2642746389

2021-05-23 21:11 UTC, vitorgalvao commented
> it seems like the SHA256 hash doesn't stay constant:

Probably why it had the `:no_check` in the first place. You can revert that.

2021-05-23 23:33 UTC, ericswpark commented
> Probably why it had the `:no_check` in the first place. You can revert that.

Done, just pushed the revert :)

2021-05-24 15:25 UTC, vitorgalvao approved these changes

2021-05-24 15:25 UTC, merged