Update 3dconnexion from 10-7-0 to 10-7-2
Homebrew/homebrew-cask-drivers pull request #2793
Opened 2022-05-07 10:05 UTC by MTCoster

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

2022-05-07 13:22 UTC, bevanjkay requested changes

2022-05-07 13:22 UTC, bevanjkay commented on Casks/3dconnexion.rb
> +  url "https://download.3dconnexion.com/drivers/mac/#{version.csv[0]}_#{version.csv[2]}/3DxWareMac_v#{version.csv[0]}_#{version.csv[1]}.dmg"
@MTCoster Generally the trend is to use `version.csv.first` / `version.csv.second` / `version.csv.third`

2022-05-07 13:22 UTC, bevanjkay commented on Casks/3dconnexion.rb
> +            launchctl: "com.3dconnexion.*",
@MTCoster I don't believe that globs are functional in launchctl, so they need to be individually listed

2022-05-08 19:06 UTC, MTCoster commented on Casks/3dconnexion.rb
> +            launchctl: "com.3dconnexion.*",
Wasn't sure about that one, thanks!

2022-05-08 19:07 UTC, MTCoster commented on Casks/3dconnexion.rb
> +  url "https://download.3dconnexion.com/drivers/mac/#{version.csv[0]}_#{version.csv[2]}/3DxWareMac_v#{version.csv[0]}_#{version.csv[1]}.dmg"
Fixed - these just came out of the old version. Is it worth also replacing the first part of the version string with `10.7.2` so it's more accurate and using a `gsub` on it get `10-7-2`?

2022-05-10 08:05 UTC, MTCoster commented
Any idea why the install is timing out on the macos-12 build agent? It works fine for me locally running Monterey 12.3.1

2022-05-11 03:01 UTC, merged